#pragma once

// enum custom_keycodes { MY_ALT_TAB = SAFE_RANGE, MY_CTRL_TAB };
enum custom_keycodes { MY_HASH = SAFE_RANGE, ESC_FOR_MAC, BSPC_FOR_MAC, MY_ALT_TAB, MY_Q, MY_W, MY_E, MY_R, MY_T, MY_Y, MY_U, MY_I, MY_O, MY_P, CLOSE_ONE_TAB_ANDROID_STUDIO, CLOSE_OTHER_TAB_ANDROID_STUDIO, CLOSE_ALL_TAB_ANDROID_STUDIO, CLOSE_ALL_TAB_LEFT_ANDROID_STUDIO, CLOSE_ALL_TAB_RIGHT_ANDROID_STUDIO, CLIPBOARD_WINDOW, CTRL_SPACE, MY_KC_PARENTHESE, MY_KC_SQUARED_CURLY_BRACKETS, MY_KC_APOSTROPHE_QUOTATION_MARKS, MY_PASSWORD_1, MY_PASSWORD_2, MY_PASSWORD_1_UPPERCASE, MY_PASSWORD_2_UPPERCASE_SYMBOL, MY_PASSWORD_1_UPPERCASE_SYMBOL };

// CMD = GUI = WIN
// CTL = CTL
// ALT = OPT

// MT - MOD (hold) | tap keycode
#define MT_CTRL_TAB MT(MOD_LCTL, KC_TAB)
#define MT_GUI_TAB MT(MOD_LGUI, KC_TAB)
#define MT_GUI_LEFT_MAC MT(MOD_LGUI, KC_LEFT)
#define MT_GUI_RIGHT_MAC MT(MOD_LGUI, KC_RIGHT)

// Hold Keycode + Keycode
#define CTRL_BSPC LCTL(KC_BSPC)   // = MT(MOD_LCTL, kc)
#define OPTION_BSPC LALT(KC_BSPC) // = MT(MOD_LALT, kc), LOPT_T(kc)

// OSL - One-shot layer
#define CHANGE_LAYER_WIN_QWERTY TG(_WIN_QWERTY)
#define CHANGE_LAYER_MAC_QWERTY TG(_MAC_QWERTY)

// LT - Hold Layer | tap KC
#define LT_WIN_FUNCTION_SPC LT(_WIN_FUNCTION, KC_SPC)
#define LT_MAC_FUNCTION_SPC LT(_MAC_FUNCTION, KC_SPC)

// MO - Momentary switch layer
#define MO_WIN_QWERTY MO(_WIN_QWERTY)
#define MO_WIN_ARROW MO(_WIN_ARROW)
#define MO_WIN_NUMBER MO(_WIN_NUMBER)
#define MO_WIN_FUNCTION MO(_WIN_FUNCTION)
#define MO_WIN_MOUSE1 MO(_WIN_MOUSE1)
#define MO_WIN_MOUSE2 MO(_WIN_MOUSE2)
#define MO_WIN_MEDIA MO(_WIN_MEDIA)
#define MO_WIN_NUM_FUNCTION MO(_WIN_NUM_FUNCTION)
#define MO_WIN_PASSWORD MO(_WIN_PASSWORD)

#define MO_MAC_QWERTY MO(_MAC_QWERTY)
#define MO_MAC_ARROW MO(_MAC_ARROW)
#define MO_MAC_NUMBER MO(_MAC_NUMBER)
#define MO_MAC_FUNCTION MO(_MAC_FUNCTION)
#define MO_MAC_MOUSE1 MO(_MAC_MOUSE1)
#define MO_MAC_MOUSE2 MO(_MAC_MOUSE2)
#define MO_MAC_MEDIA MO(_MAC_MEDIA)
#define MO_MAC_NUM_FUNCTION MO(_MAC_NUM_FUNCTION)
#define MO_MAC_PASSWORD MO(_MAC_PASSWORD)

// #define SFT_EQ MT(MOD_LSFT, KC_EQL)
// #define SFT_QT MT(MOD_RSFT, KC_QUOT)

// #define SFT_A MT(MOD_LSFT, KC_A)
// #define CTL_Z MT(MOD_LCTL, KC_Z)
// #define SFT_SCLN MT(MOD_RSFT, KC_SCLN)
// #define CTL_SLSH MT(MOD_RCTL, KC_SLSH)

// #define RAI_EQ LT(_RAISE, KC_EQL)
// #define RAI_ENT LT(_RAISE, KC_ENT)
// #define LOW_BSP LT(_LOWER, KC_BSPC)
// #define LOW_DEL LT(_LOWER, KC_DEL)
// #define ADJ_GRV LT(_ADJUST, KC_GRV)
// #define KC_ANGL LSFT(KC_COMM)
// #define KC_ANGR LSFT(KC_DOT)
